### ISSUE TITLE
BUG: Fail to load on second run.

### ISSUE THREAD

**Issue by JordanGS** [JordanGS/workspace#1]
**Project: OWASP ZAP Extension - Export Report**

`3012 [ZAP-BootstrapGUI] ERROR org.parosproxy.paros.extension.ExtensionLoader  - 
java.lang.NullPointerException
 at org.zaproxy.zap.extension.exportReport.ExtensionExportReport.getDescription(ExtensionExportReport.java:160)
 at org.parosproxy.paros.extension.ExtensionLoader.hookAllExtension(ExtensionLoader.java:660)
 at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(ExtensionLoader.java:536)
 at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:57)
 at org.parosproxy.paros.control.Control.init(Control.java:114)
 at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:286)
 at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:200)
 at org.zaproxy.zap.GuiBootstrap.access$1(GuiBootstrap.java:199)
 at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:144)
 at java.lang.Thread.run(Unknown Source)`

The thing to note is the getDescription(), attempts to get the value from a textfield/textarea. This happens to all of the components on the first panel. So i suspect the issue has to do with the FrameExportReport.java class and how i initialize the panels, something there ZAP doesn't like.

**Comment by JordanGS** [comment]
**Fixed for v1.0 release!**
